### ISSUE TITLE
録画済み番組の削除でクラッシュする

### ISSUE THREAD

**Issue by eru** [Harekaze/Harekaze-iOS#11]
### Description

既にクラッシュレポートなどで判明しているかもしれませんが、issue書いておきます。

Recordings->番組選択->More->Delete押下でクラッシュします。

### Steps to Reproduce

1. Recordingsから番組を選択
2. More
3. Deleteを押下
4. 確認でDeleteを押下

#### Hardware
- iPhone X
- iPadPro 10.5インチ

#### Software
- iOS 11.2.5

#### Jailbreak
- Not-Jailbroken

### Versions
- Harekaze for iOS: 1.0.0 build 0.1
- Chinachu: 3410e1061c719e9a1f6e6ae905173f2eaa6cd14e
- Mirakurun: v2.5.7

**Comment by mzyy94** [comment]
Realmデータベースの扱いが複雑になっており、参照するデータの不整合が発生してしまっているようです。
こちら優先して修正いたしますので少々おまちください。

**Comment by mzyy94** [comment]
Fixed c77c29ad7dab78e28e63cd943839c577b006a9e7
