### ISSUE TITLE
プレイヤーのメニューが開かない

### ISSUE THREAD

**Issue by eru** [Harekaze/Harekaze-iOS#12]
### Description

番組再生中プレイヤーのオーバーレイで表示される右上の「・・・」メニューをタップしても何も起こらない。
（また、実装してないということであれば、すいません。）

### Steps to Reproduce

1. Recordingsから番組を選択
2. Play
3. オーバーレイの「・・・」をタップ

#### Hardware
- iPhone X
- iPadPro 10.5インチ

#### Software
- iOS 11.2.5

#### Jailbreak
- Not-Jailbroken

### Versions
- Harekaze for iOS: 1.0.0 build 0.1
- Chinachu: 3410e1061c719e9a1f6e6ae905173f2eaa6cd14e
- Mirakurun: v2.5.7

**Comment by mzyy94** [comment]
忘却してました。
音声や画像の設定項目を出す予定でいたのですがバージョン1.0では実装を見送る方針でいますので、このボタンは削除します。

**Comment by mzyy94** [comment]
Fixed 24f344484f79c04f343bfcdc4126baf9ab3b9195
