### ISSUE TITLE
ヘッダ部分が表示されなくなる

### ISSUE THREAD

**Issue by eru** [Harekaze/Harekaze-iOS#13]
### Description

下部の「Recordings」のメニューを押下し、番組詳細から戻ると上部の表示中のメニュー名が表示されている部分が白枠だけになる。

下記の再現手順は「Recordings」の場合ですが、他の「Timers」や「Guide」などでも同様の手順で発生します。

### Steps to Reproduce

1. Recordingsから番組を選択
2. 下部のSearchメニューをタップ
3. 下部のRecordingsをタップ
4. 下部のRecordingsをタップ

※ 1度発生した後は、2でSearch以外のメニューをタップしても、TimersやGuideでも発生します。

#### Hardware
- iPhone X
- iPadPro 10.5インチ

#### Software
- iOS 11.2.5

#### Jailbreak
- Not-Jailbroken

### Versions
- Harekaze for iOS: 1.0.0 build 0.2
- Chinachu: a69d5e99b75ddd770146e65d6171704be28ec01a
- Mirakurun: v2.6.1

**Comment by mzyy94** [comment]
うーむ,,,修正しているつもりなのですが、、  b6a7abd3d0d3c9c8e17434bbe95b69cd3a7771f5
こちらでは再現せず修正ができませぬ。。追って変化があれば報告お願いします。。。

**Comment by eru** [comment]
手元で確実に再現する方法を改めて確認し、追記しましたのでご確認ください。

**Comment by eru** [comment]
一度Searchの画面を表示してしまえば、下部のメニュータップで詳細から戻る際に発生するようです

**Comment by mzyy94** [comment]
再現しました。修正しました 0f0e1f51698108ce1bf811eb1ca682d7fc1fa34e 。
RC-4に取り込みます。
