### ISSUE TITLE
Guideのチャンネル部分の一部が表示されない場合がある

### ISSUE THREAD

**Issue by eru** [Harekaze/Harekaze-iOS#14]
### Description

起動後恐らく？バックエンドでGuideの情報を取得しているのかと思いますが、それが完了した後にGuideを表示すると一部のチャンネル表示部分が表示されず、左右にスクロールしてもその部分が表示されないままとなります。

iPad Pro 10.5インチでのみ発生し、縦・横問わずに発生します。

問題の動作がわかりにくいかと思ったので一応動画を上げておきます。
https://photos.app.goo.gl/2qXZuwbm9Ea886KY2

### Steps to Reproduce

1. アプリを完全に終了する
2. 起動後10秒程度待機
3. Guideをタップ

#### Hardware
- iPadPro 10.5インチ

#### Software
- iOS 11.2.5

#### Jailbreak
- Not-Jailbroken

### Versions
- Harekaze for iOS: 1.0.0 build 0.2
- Chinachu: a69d5e99b75ddd770146e65d6171704be28ec01a
- Mirakurun: v2.6.1

**Comment by mzyy94** [comment]
再現しました。修正しました 85a3ff5fd56b54e598da5e954afd8c8eb589e244 。
RC-4に取り込みます。
