### ISSUE TITLE
ダウンロードの削除後、再度ダウンロードが行えない

### ISSUE THREAD

**Issue by eru** [Harekaze/Harekaze-iOS#15]
### Description

番組のダウンロード後に、ダウンロードしたものを削除するとメニュー上にDOWNLOADが表示されなくなりアプリを再起動するまでダウンロードを行うことができなくなります。

### Steps to Reproduce

1. Recordingsから番組を選択
2. メニューからDOWNLOADをタップ
3. Recordingsへ戻る
4. ダウンロード完了後、1の番組を選択
5. メニューからDELETE DOWNLOADをタップ(自動的にRecordingsへ戻る)
6. 1の番組を選択
7. メニューをタップ

#### Hardware
- iPhone X
- iPad Pro 10.5インチ

#### Software
- iOS 11.2.5

#### Jailbreak
- Not-Jailbroken

### Versions
- Harekaze for iOS: 1.0.0 build 0.3
- Chinachu: a69d5e99b75ddd770146e65d6171704be28ec01a
- Mirakurun: v2.6.1

**Comment by mzyy94** [comment]
Fixed 1ba3282040a862bb9b5bc17b47934d771bba2b6b
