### ISSUE TITLE
ダウンロード済みの番組を削除するとクラッシュする

### ISSUE THREAD

**Issue by eru** [Harekaze/Harekaze-iOS#16]
### Description

Downloadsからダウンロード済みの番組を削除するとクラッシュする

### Steps to Reproduce

1. Recordingsから番組を選択
2. メニューからDOWNLOADをタップ
3. ダウンロード完了後、Downloadsから1の番組を選択
2. メニューからDELETEをタップ
3. 確認のDELETEをタップ

#### Hardware
- iPhone X
- iPad Pro 10.5インチ

#### Software
- iOS 11.2.5

#### Jailbreak
- Not-Jailbroken

### Versions
- Harekaze for iOS: 1.0.0 build 0.3
- Chinachu: a69d5e99b75ddd770146e65d6171704be28ec01a
- Mirakurun: v2.6.1

**Comment by mzyy94** [comment]
なぜかこちらで再現できなかったので様子見を続けてください

**Comment by eru** [comment]
手元の環境で 217e99d をビルドして、クラッシュ時のログ見てみましたがこんな感じでした。

```
2018-02-26 22:39:56.712256+0900 Harekaze[26818:3268358] [Answers] Logging Answers event: <ANSCustomEvent: File download info
{
    "file size" = 28062572;
    transcode = 0;
}>
2018-02-26 22:40:01.936505+0900 Harekaze[26818:3269870] Task <D10EBBA5-ED12-45F6-AC93-FBD54EEF919C>.<3> finished with error - code: -1001
2018-02-26 22:40:05.733158+0900 Harekaze[26818:3268358] *** Terminating app due to uncaught exception 'RLMException', reason: 'Can only delete an object from the Realm it belongs to.'
*** First throw call stack:
(0x181c7b164 0x180ec4528 0x103d709b8 0x1047170b8 0x100cf1a1c 0x1047159e8 0x100cf1774 0x100c65fec 0x100cd06e4 0x102d709e8 0x102d53540 0x102d53284 0x10585d2cc 0x10585d28c 0x105861ea0 0x181c23344 0x181c20f20 0x181b40c58 0x1839ecf84 0x18b2995c4 0x100c84e14 0x18166056c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by mzyy94** [comment]
Downloadsから番組詳細を開いた場合、[ProgramDetailTableViewController.swift#L64](https://github.com/Harekaze/Harekaze-iOS/blob/a2c122c06888188f44fca66edfe8fc2592f8ec42/Harekaze/ViewControllers/Common/ProgramDetailTableViewController.swift#L64)の`self.recording`が`nil`のままであり、[ProgramDetailTableViewController.swift#L376](https://github.com/Harekaze/Harekaze-iOS/blob/a2c122c06888188f44fca66edfe8fc2592f8ec42/Harekaze/ViewControllers/Common/ProgramDetailTableViewController.swift#L376)がRealmデータベースにて共有扱いの`self.program`を参照し、削除してしまっているのが原因ということがわかりました。
`self.download`のイニシャライズ時に`self.recording`への代入処理を行う工夫を組むとともに、DELETEボタンの出現条件を`self.recording`の`nil`チェックを元に分岐させ、L376での参照を`self.recordings`にすることで修正を行います。また、APIのIDの値渡しが今回のような不具合を生みやすくしていることも考慮し、APIへはIDを渡すのではなくオブジェクトを渡す形に変更していく所存です。

**Comment by mzyy94** [comment]
Fixed b5cd29b88275e4bc0618ab71762f7d961780821c
