### ISSUE TITLE
Recordingsからのダウンロードの削除時の動きについて

### ISSUE THREAD

**Issue by eru** [Harekaze/Harekaze-iOS#17]
### Description

Recordings（以下、一覧）の番組詳細画面内のメニューからのダウンロードの削除時に、自動的に一覧へ戻りますが、自身の削除ではないため、一覧へ戻る必要がないように思えますが、いかがでしょうか？

### Steps to Reproduce

1. Recordingsから番組を選択
2. メニューからDOWNLOADをタップ
3. Recordingsへ戻る
4. ダウンロード完了後、1の番組を選択
5. メニューからDELETE DOWNLOADをタップ

#### Hardware
- iPhone X
- iPad Pro 10.5インチ

#### Software
- iOS 11.2.5

#### Jailbreak
- Not-Jailbroken

### Versions
- Harekaze for iOS: 1.0.0 build 0.3
- Chinachu: a69d5e99b75ddd770146e65d6171704be28ec01a
- Mirakurun: v2.6.1

**Comment by mzyy94** [comment]
番組詳細画面自体がどこの画面から遷移してきたかをチェックしてなかったので、現在のビューにおいてリソースが更新された前提の戻る挙動を行なっていました。
おっしゃる通り、Recordingsにまだ存在している場面においては戻る必要がなさそうなので、遷移元画面の関連性から挙動をぶんきさせる形で対処したいと思います。

**Comment by mzyy94** [comment]
Fixed 1648d65799ea9e27cb3912aab0fc048308e05c1b
