### ISSUE TITLE
Timersのカテゴリ背景色が変化する

### ISSUE THREAD

**Issue by eru** [Harekaze/Harekaze-iOS#18]
### Description

カテゴリ: varietyの番組のタイマーの背景色が、起動後初めてTimersを開いたタイミングで、ピンク -> 黄色に変化する。

動画: https://photos.app.goo.gl/81zY0Mj3FdY2iks33

### Steps to Reproduce

1. varietyカテゴリの番組を予約する
2. Timersをタップして表示

#### Hardware
- iPhone X
- iPad Pro 10.5インチ

#### Software
- iOS 11.2.5

#### Jailbreak
- Not-Jailbroken

### Versions
- Harekaze for iOS: 1.0.0 build 0.4
- Chinachu: a69d5e99b75ddd770146e65d6171704be28ec01a
- Mirakurun: v2.7.0

**Comment by mzyy94** [comment]
[ProgramItemTableViewCell.swift#L74](https://github.com/Harekaze/Harekaze-iOS/blob/master/Harekaze/Views/ProgramItemTableViewCell.swift#L74)での色の変更処理が即時反映されていないようですね（なぜだ）。
`setNeedsDisplay`でも追加して変更を刺激してみますね。

**Comment by mzyy94** [comment]
maybe fixed 933d283593dc8e4e597554a109880b3ea97b7f49

**Comment by mzyy94** [comment]
Also fixed 927caf679f50b7d85c335b25b820b44d2ea18f69
