### ISSUE TITLE
終端まで再生した時に再生コントロール系のボタンが効かなくなる

### ISSUE THREAD

**Issue by eru** [Harekaze/Harekaze-iOS#3]
### Description

録画済みファイルを終端まで再生すると高確率で再生コントロール系のボタンが効かなくなります。
### Steps to Reproduce
1. Recordingsより、録画済みのものを再生
2. 終端まで再生
- 発生確率が100%ではありませんが、10回に7回程度の割合で発生します。
#### Hardware
- iPhone 6s
- iPad Air 2
#### Software
- iOS 9.3.5
#### Jailbreak
- Not-Jailbroken
### Versions
- Harekaze for iOS: v1.0.0-beta9
- Chinachu: beta 7a43f80
- Mirakurun: v1.7.1

**Comment by mzyy94** [comment]
この問題はこちらでも多々発生しており、解決に向けた取り組みを考案中です。
今しばらくお待ちください。

**Comment by mzyy94** [comment]
再生終了したらプレイヤー閉じますね。

**Comment by mzyy94** [comment]
Fixed a07d2c3e8446a5f0df094dbcb991205e0a77536a
