### ISSUE TITLE
テザリング時に描画が崩れる

### ISSUE THREAD

**Issue by mizucoffee** [Harekaze/Harekaze-iOS#7]
### Description

テザリング中、上に接続台数等が表示されているときに起動すると、Androidで言うActionBarの描画が崩れます。

![img_1046](https://cloud.githubusercontent.com/assets/9247699/19624536/67219b34-9935-11e6-9c2c-44a349bbfcc4.PNG)

※テーブルの内容は後から加工して消しています

![img_1045](https://cloud.githubusercontent.com/assets/9247699/19624535/628d5a36-9935-11e6-841d-af234c5dafb5.PNG)

### Steps to Reproduce

1. テザリングをする
2. 1台以上接続する
3. その状態でHarekazeを起動する
#### Hardware
- iPhone 6
#### Software
- iOS 10.0.2
#### Jailbreak
- Not-Jailbroken
### Versions

- Harekaze for iOS: 10.0.X-beta10
- Chinachu: beta 0.0.1 4dfda4af0552745f8b0bff876d1bff33746f33e5
- Mirakurun: v2.0.0-beta.0

**Comment by mzyy94** [comment]
事象の再現を確認しました。現在マテリアルデザイン部分は外部のライブラリを利用しており、特にナビゲーションバー部分は不具合が多く、対処に時間がかかっております。
依存しているライブラリ側の修正がなければ、Storeに出すタイミングで実装の変更を考えています。現状はこのIssueをPending状態とし、ライブラリの状況を見ながら対応して行きます。
ご報告ありがとうございました。😊

**Comment by mzyy94** [comment]
事象の再現を確認しました。現在マテリアルデザイン部分は外部のライブラリを利用しており、特にナビゲーションバー部分は不具合が多く、対処に時間がかかっております。
依存しているライブラリ側の修正がなければ、Storeに出すタイミングで
実装の変更を考えています。現状はこのIssueをPending状態とし、ライブラリの状況を見ながら対応して行きます。
ご報告ありがとうございました。😊

**Comment by mzyy94** [comment]
同様の問題はiPhone XのUI構造の変更にも影響しており、大変な労力をかけることとなりました。

https://twitter.com/mzyy94/status/926704412705284096

丸みのあるコンポーネントを用いるシステムデザインに追従するといった方転換により、デザインの大幅変更が加わったため、本マテリアルデザインに関する問題は影響の範囲外となりました。
Closeします。
