### ISSUE TITLE
Recordingsについて

### ISSUE THREAD

**Issue by mizucoffee** [Harekaze/Harekaze-iOS#8]
### Description

Recordingsを録画済みのメニューとして使っていますが、Recordedではないでしょうか。
もし、意図があればCloseしていただいて全然構いません。

**Comment by mzyy94** [comment]
英文化圏では、Recordingは録画を示す**名詞**として広く使われています。
Recordの動名詞としてRecord+ingで録画中を表すこともありますが、あくまでも動詞を用いた現在進行の動作を示す目的となります。
また、Recorded単体では、「録画（録音）済みの～」といった形容詞としての意味しか持たないため、一単語で示すのは適当ではありません。
Recordedを用いる場合は、Recorded Programsなどと冗長な表現にすることが推奨されます。
また、pvr.chinachuの動作対象となるKodiでもRecordingsという表記が用いられていることから、
このプロジェクトでは、全体を通して録画を示す名詞Recordingの複数形の単語として**Recordings**を用いています。
